### ISSUE TITLE
Got error with this tools

### ISSUE THREAD

**Issue by royxue** [derekpeterson/generator-react-flask#1]
main.bundle.js:4 Uncaught ReferenceError: production is not defined

I got this error when I use your tools to create a project, how can I fix it?

thx

**Comment by royxue** [comment]
Solved this, see => #2

**Comment by derekpeterson** [comment]
Thanks for the report and PR! I'll take a look this evening.

**Comment by derekpeterson** [comment]
Fixed by #2, and released in v1.0.5. Thanks!
